title: Mahmoud Alboredy
#logo: /assets/img/headshot_circle.png
description: Iâ€™m an active professional with extensive experience in customer communication and process optimization within the telecommunications industry. Proficient at complaints handling and conflict resolution. Skilled in SharePoint management, MS Power Platform, and MS Office.
#show_downloads: false
theme: jekyll-theme-minimal
